import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./utils/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const logout = async () => {
    const resp = await fetch("http://localhost:3000/api/auth/logout");
  };
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
